name: Build and release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      ghc_version:
        description: "GHC version to install"
        required: true
        default: "9.4.8"
      cabal_version:
        description: "Cabal version to install"
        required: true
        default: "3.10.3.0"
  push:
    branches:
      - main
    inputs:
      ghc_version:
        description: "GHC version to install"
        required: false
        default: "9.4.8"
      cabal_version:
        description: "Cabal version to install"
        required: false
        default: "3.10.3.0"

jobs:
  build:
    name: Build and release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Make scripts executable
        run: |
          chmod +x ./scripts/build_linux.sh
          chmod +x ./scripts/build_macos.sh

      - name: Build on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          ./scripts/build_linux.sh
          mv *.tar.gz chequera-linux.tar.gz

      - name: Build on macOS
        if: matrix.os == 'macos-latest'
        run: |
          ./scripts/build_macos.sh
          mv *.tar.gz chequera-macos.tar.gz

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chequera-${{ runner.os }}
          path: "*.tar.gz"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.tar.gz"
          name: "Release ${{ env.VERSION }}" # Sets/updates release title
          tag_name: "v${{ env.VERSION }}" # Sets/updates tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
